export const catJokes = {
  nl: [
    "404: Oeps, geen Luca de huiskat te bekennen hier! Of een pagina. Maar vooral geen Luca. 😿",
    "404: De pagina is weg... We geven Luca de huiskat de schuld. Dat werkt altijd. 😼",
    "404: Luca raakte afgeleid door een bolletje wol. En nu zijn we deze pagina kwijt. Miauw? 🧶",
    "404: Je zocht een pagina? Luca de huiskat had belangrijkere dingen te doen. Zoals slapen. 💤",
    "404: Luca's kattenlogica toegepast. Als ik het niet zie, bestaat het niet. Net als deze pagina. 🙈",
    "404: Pagina is spoorloos. Luca is waarschijnlijk door de laserpointer afgeleid. 🔴",
    "404: Pagina niet gevonden. Luca zit waarschijnlijk ergens op een warm toetsenbord te chillen. ⌨️",
    "404: Deze pagina is ge-'cat'-astreerd. Luca dacht dat het een muis was. Oeps. 🐭",
    "404: Jij weer?! Wat zoek je hier steeds? Luca verzekert je dat er echt geen tonijn verstopt is, beloofd. 🐟",
    "404: Terug voor meer? Deze pagina is nog steeds leeg. Net als Luca's voerbak om 04:00 's ochtends. 🍽️",
    "404: Serieus, alweer? Zelfs Luca de huiskat kijkt je nu veroordelend aan. 😒",
    "404: Luca de huiskat is op onderzoek uit gegaan... Maar zelfs hij snapt niet waarom je hier steeds komt. 🕵️‍♂️",
    "Luca is nog steeds op vakantie. Of op jacht. Of in een doos. Misschien vind je 'm sneller met een kattenbelletje? 🔔",
    "404: De pagina is niet hier. Jij wél. We beginnen een band te krijgen. Wil je misschien een bakje melk terwijl je wacht? 🥛",
    "Oké... wat is jouw plan hier? De pagina is NIET hier. Ook niet bij het kattenluik. Maar we bewonderen je doorzettingsvermogen. 🚪",
    "Een mysterieuze bezoeker blijft terugkeren naar de verloren pagina. Verdacht gedrag. Luca verdenkt je van snacks. 🥨",
    "\"Ik ben een kat. Ik snap dat je koppig bent. Respect.\" Maar zelfs ik weet wanneer ik moet stoppen met op de printer springen. 🖨️",
    "Je hebt Luca's aandacht. Dat gebeurt niet snel. Hij kijkt nu met één oog open naar je. Niet vanwege de pagina, maar uit respect. 👁️",
    "Luca is ondertussen verhuisd naar een andere kamer. Hij zegt: \"Als jij hier blijft klikken, dan breng ik wel snacks.\" 🍪",
    "Er is nog steeds geen pagina. Maar je krijgt wél een kopje en een trillende staart. Miauw = respect. 🤝",
    "Hij ligt ondersteboven op de bank. Jij zit nog steeds hier. Misschien zijn jullie beiden aan het wachten tot er iets magisch gebeurt? ✨",
    "Hij droomt van een wereld waar alle 404-pagina's muisvormig zijn. Jij? Jij zit vast in de matrix. 💊",
    "Wist je dat Luca je nu officieel als onderdeel van het huishouden ziet? Hij heeft je territorium gemarkeerd. Welkom bij de familie. 🏠",
    "Luca heeft een theorie. Misschien ben jij de pagina. Misschien was de 404 in ons allemaal. 🌌",
    "GEFELICITEERD! Je hebt de Luca Achievement vrijgespeeld: \"Koppigheid der Katten.\" Nog steeds geen pagina, maar wel eeuwige kattenglorie. 🏅",
    "Luca heeft een doos voor je klaargezet. Geen idee waarom je hier nog bent, maar de doos is warm. En zacht. Je mag er in, zegt Luca. 📦",
    "Luca is transcendent gegaan. Hij zweeft boven ruimte en tijd. Jij daarentegen... zit nog steeds op de 404. Respect. 🧘‍♂️",
    "Luca doet nu onderzoek. Hij heeft een vergrootglas (oké, soort van). Hij snuffelt rond. Maar zelfs hij vindt geen spoor van die vermiste pagina. 🔍",
    "Je hebt nu meer tijd op deze 404 gespendeerd dan Luca aan zijn etensbak. En geloof ons... dat is veel. ⏳",
    "Luca kijkt nu theatraal uit het raam. \"Misschien keert de pagina terug met de regen,\" fluistert hij dramatisch. Jij kijkt mee. Samen wachten jullie. 🌧️",
    "Luca probeert nu gewoon de pagina uit te graven. Onder de kast. In de plantenbak. Achter de gordijnen. Geen resultaat. Wel veel zand. 🪴",
    "Luca heeft het geaccepteerd. Deze pagina is voorgoed verdwenen. Hij heeft het in zijn kattengeheugen opgeslagen als een mysterie dat nooit opgelost zal worden. 🧠",
    "Luca mediteert. Over vergankelijkheid. Over lege webpagina's. Over mensen die blijven klikken. Over jou. 🕉️",
    "Luca heeft een portaal geopend. Geen idee hoe. Maar het ruikt naar tonijn. Ga je erin, of klik je nóg een keer? 🌀",
    "Luca spreekt. \"Wie klikt, zal vinden. Maar misschien niet wat hij zoekt.\" En toen likte hij z'n poot en liep weg. 📜",
    "Luca heeft een boek geschreven. \"Hoe ik 404 keer een pagina zocht en alleen maar een mens vond.\" Bestseller onder katten. 📚",
    "Luca heeft een dobbelsteen gegooid. Als het zes wordt, komt de pagina terug. Het werd een pootafdruk. 🎲",
    "Luca kijkt je nu echt recht aan. Zonder knipperen. Jullie delen een moment. Een klik. Geen web-klik. Een ziels-klik. ❤️",
    "Luca heeft z'n brokjes opgegeten, een dutje gedaan en zit weer op z'n uitkijkpost. Jij bent er nog steeds. Hij begint je echt te waarderen. 😻",
    "Luca heeft een signaal naar de ruimte gestuurd. \"Help. Mens blijft klikken. Stuur pagina. Of speeltje met veer.\" Geen antwoord. Alleen een miauw in de leegte. 📡",
    "Luca is een mythe geworden. De legende van de kat die de 404 bewaakte. En van de bezoeker die nooit opgaf. 🏛️",
    "Luca heeft een interdimensionale tunnel gegraven. Aan de andere kant? ...Ook geen pagina. Maar wel een eindeloze voorraad kattensnoepjes. 🍬",
    "CONGRATULATIES! Je hebt het 404-einde bereikt. Er is geen prijs. Geen geheim. Geen pagina. Alleen Luca. En jij. Voor altijd. ♾️",
  ],
  en: [
    "404: Oops, no Luca the house cat to be found here! Or a page. But especially no Luca. 😿",
    "404: The page is gone... We blame Luca the house cat. That always works. 😼",
    "404: Luca got distracted by a ball of yarn. And now we lost this page. Meow? 🧶",
    "404: Looking for a page? Luca the house cat had more important things to do. Like sleeping. 💤",
    "404: Luca's cat logic applied. If I can't see it, it doesn't exist. Just like this page. 🙈",
    "404: Page is missing. Luca was probably distracted by the laser pointer. 🔴",
    "404: Page not found. Luca is probably chilling on a warm keyboard somewhere. ⌨️",
    "404: This page has been cat-astrophically lost. Luca thought it was a mouse. Oops. 🐭",
    "404: You again?! What are you looking for here? Luca assures you there's really no tuna hidden, promise. 🐟",
    "404: Back for more? This page is still empty. Just like Luca's food bowl at 4:00 AM. 🍽️",
    "404: Seriously, again? Even Luca the house cat is looking at you judgmentally now. 😒",
    "404: Luca the house cat went investigating... But even he doesn't understand why you keep coming here. 🕵️‍♂️",
    "Luca is still on vacation. Or hunting. Or in a box. Maybe you'll find him faster with a cat bell? 🔔",
    "404: The page is not here. You are. We're starting to bond. Would you like a bowl of milk while you wait? 🥛",
    "Okay... what's your plan here? The page is NOT here. Not by the cat flap either. But we admire your perseverance. 🚪",
    "A mysterious visitor keeps returning to the lost page. Suspicious behavior. Luca suspects you of snacks. 🥨",
    "\"I'm a cat. I understand you're stubborn. Respect.\" But even I know when to stop jumping on the printer. 🖨️",
    "You have Luca's attention. That doesn't happen often. He's now looking at you with one eye open. Not because of the page, but out of respect. 👁️",
    "Luca has moved to another room. He says: \"If you keep clicking here, I'll bring snacks.\" 🍪",
    "There's still no page. But you do get a head bump and a trembling tail. Meow = respect. 🤝",
    "He's lying upside down on the couch. You're still here. Maybe you're both waiting for something magical to happen? ✨",
    "He dreams of a world where all 404 pages are mouse-shaped. You? You're stuck in the matrix. 💊",
    "Did you know Luca now officially sees you as part of the household? He's marked your territory. Welcome to the family. 🏠",
    "Luca has a theory. Maybe you are the page. Maybe the 404 was in all of us. 🌌",
    "CONGRATULATIONS! You've unlocked the Luca Achievement: \"Stubbornness of Cats.\" Still no page, but eternal cat glory. 🏅",
    "Luca has set up a box for you. No idea why you're still here, but the box is warm. And soft. You can get in, says Luca. 📦",
    "Luca has gone transcendent. He floats above space and time. You, on the other hand... are still on the 404. Respect. 🧘‍♂️",
    "Luca is now investigating. He has a magnifying glass (sort of). He's sniffing around. But even he finds no trace of that missing page. 🔍",
    "You've now spent more time on this 404 than Luca at his food bowl. And believe us... that's a lot. ⏳",
    "Luca is now theatrically looking out the window. \"Maybe the page returns with the rain,\" he whispers dramatically. You look along. Together you wait. 🌧️",
    "Luca is now just trying to dig up the page. Under the cabinet. In the plant pot. Behind the curtains. No result. But lots of sand. 🪴",
    "Luca has accepted it. This page is gone forever. He has stored it in his cat memory as a mystery that will never be solved. 🧠",
    "Luca meditates. About transience. About empty web pages. About people who keep clicking. About you. 🕉️",
    "Luca has opened a portal. No idea how. But it smells like tuna. Will you go in, or click one more time? 🌀",
    "Luca speaks. \"Who clicks, shall find. But maybe not what he seeks.\" And then he licked his paw and walked away. 📜",
    "Luca has written a book. \"How I searched for a page 404 times and only found a human.\" Bestseller among cats. 📚",
    "Luca rolled a dice. If it becomes six, the page returns. It became a paw print. 🎲",
    "Luca is now really looking you straight in the eye. Without blinking. You share a moment. A click. Not a web click. A soul click. ❤️",
    "Luca has eaten his kibbles, took a nap and is back at his lookout. You're still here. He's really starting to appreciate you. 😻",
    "Luca has sent a signal to space. \"Help. Human keeps clicking. Send page. Or feather toy.\" No answer. Just a meow in the void. 📡",
    "Luca has become a myth. The legend of the cat who guarded the 404. And of the visitor who never gave up. 🏛️",
    "Luca has dug an interdimensional tunnel. On the other side? ...Also no page. But an endless supply of cat treats. 🍬",
    "CONGRATULATIONS! You've reached the 404 ending. There's no prize. No secret. No page. Only Luca. And you. Forever. ♾️",
  ],
}

export const achievements = {
  nl: {
    10: { title: "Klikkoning(in)", description: "Je hebt 10 keer op Luca geklikt! Je bent officieel een klikexpert!" },
    20: { title: "Voermeester", description: "Je hebt 20 keer op Luca geklikt! Luca vindt je een geweldige voermeester!" },
    30: { title: "Wolkampioen", description: "Je hebt 30 keer op Luca geklikt! Niemand speelt beter met wol dan jij!" },
    99: { title: "Portaalontdekker", description: "Je hebt 99 keer op Luca geklikt! Een magisch portaal verschijnt..." },
  },
  en: {
    10: { title: "Click Champion", description: "You clicked on Luca 10 times! You're officially a click expert!" },
    20: { title: "Food Master", description: "You clicked on Luca 20 times! Luca thinks you're a great food master!" },
    30: { title: "Wool Champion", description: "You clicked on Luca 30 times! Nobody plays with wool better than you!" },
    99: { title: "Portal Discoverer", description: "You clicked on Luca 99 times! A magical portal appears..." },
  },
}
